name: paperopoli_terminal
description: Paperopoli Terminal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  ionicons: ^0.1.2
  firebase_auth: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  timelines: ^0.1.0
  collection: ^1.15.0
  flutter_calendar_carousel: ^2.0.1
  fl_chart: ^0.36.1
  lottie: ^1.0.1
  google_fonts: ^2.1.0
  auto_animated: ^3.0.0
  flash: ^2.0.0
  date_time_picker: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  pedantic: ^1.11.0
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Heavy.ttf  
          weight: 900 
        - asset: assets/fonts/SFProDisplay-Black.ttf  
          weight: 800 
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700 
        - asset: assets/fonts/SFProDisplay-Semibold.ttf  
          weight: 600 
        - asset: assets/fonts/SFProDisplay-Medium.ttf  
          weight: 500 
        - asset: assets/fonts/SFProDisplay-Regular.ttf  
          weight: 400 
        - asset: assets/fonts/SFProDisplay-Light.ttf  
          weight: 300 
        - asset: assets/fonts/SFProDisplay-Ultralight.ttf  
          weight: 200 
        - asset: assets/fonts/SFProDisplay-Thin.ttf  
          weight: 100

flutter_native_splash:
  image: assets/images/icon.png
  color: "#ffffff"
  android_disable_fullscreen: true    